baseURL = 'https://theseluckystars.com'
languageCode = 'en-us'
title = 'These Lucky Stars'
theme = 'hugo-book'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# CUSTOM MENU ITEMS

[[menu.after]]
  name = "---"
  weight = 1
  
[[menu.after]]
  name = "Character Sheet"
  url = "/digitalcharactersheet.html"
  weight = 2

[[menu.after]]
  name = "Attribute Converter"
  url = "/attributeconverter.html"
  weight = 3

[[menu.after]]
  name = "Planet Generator"
  url = "/planetnamegenerator.html"
  weight = 4

# BOOK THEME PARAMETERS

[params]
  # Theme: 'light', 'dark', or 'auto' (follows browser/OS preference)
  BookTheme = 'auto'
  
  # Path to logo and favicon (relative to /static/)
  BookLogo = 'logo.png'
  
  # Table of Contents - global setting
  BookToC = true
  
  # Menu section - which content folder generates menu
  # Use '*' for all sections, 'docs' for just /docs/
  BookSection = 'docs'
  
  # Date format
  BookDateFormat = 'January 2, 2006'
  
  # Search functionality (uses FlexSearch)
  BookSearch = true
  
  # Comments (uses Disqus if configured)
  BookComments = false

  # Caching for PWA
  BookServiceWorker = "precache"